### ISSUE TITLE
This problem occurs

### ISSUE THREAD

**Issue by AOSP-sm8150** [stuartore/aosp-setup#1]
$ ./aosp.sh
=> Found non-English direcotory string [8150]
=> Suggestions: rename it in Eng.

**Comment by stuartore** [comment]
Please clone aosp-setup under an English named directory. eg. `/home/{Your_name}/` or other directory.

It's because in some cases error occurs when building aosp ROM packages under a non-English directory .

If you desire to run it, try to search `aosp_setup_check $aosp_setup_dir_check_ok` and add '#' before it:
```
# aosp_setup_check $aosp_setup_dir_check_ok
```

**Comment by AOSP-sm8150** [comment]
Ok, it’s ready to use. Thank you very much for your reply.

**Comment by stuartore** [comment]
You're welcome.

**Comment by stuartore** [comment]
> Ok, it’s ready to use. Thank you very much for your reply.

You're welcome.
